### ISSUE TITLE
Too many agents connected error

### ISSUE THREAD

**Issue by sbaier1** [mqtt-varroa/varroa#151]
While testing on Terraform with 3 agents created and trying to connect to the commander
```java
 docker run --name varroa_commander --rm -p 9000:9000 -v /Users/sbaier/IdeaProjects/varroa-terraform/commander.xml:/opt/commander.xml -v /Users/sbaier/IdeaProjects/varroa-terraform/scenario_car.xml:/opt/scenario.xml varroa/varroa -I /opt/commander.xml -S /opt/scenario.xml
2019-05-15 11:29:05,192 INFO  - Commander - Waiting for Agents 0/3.
2019-05-15 11:29:07,529 INFO  - Commander - Waiting for Agents 1/3.
2019-05-15 11:29:07,543 INFO  - Commander - Waiting for Agents 2/3.
2019-05-15 11:29:07,546 INFO  - Commander - All Agents connected.
2019-05-15 11:29:07,623 INFO  - Commander - Server channel closed.
2019-05-15 11:29:07,656 WARN  - ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xdfb73069, L:/172.17.0.3:9000 - R:/172.17.0.1:49332]
java.lang.IllegalStateException: too many agents connected
        at org.varroa.remote.commander.CommanderChannels.addChannel(CommanderChannels.java:71)
        at org.varroa.remote.commander.CommanderChannelInitializer.initChannel(CommanderChannelInitializer.java:47)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:427)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
2019-05-15 11:29:07,924 INFO  - Commander - Scenario data distributed.
2019-05-15 11:29:07,926 INFO  - Commander - Scenario in progress: Stage with id 'status-subscription' (1/3).
2019-05-15 11:29:08,544 INFO  - Commander - Scenario in progress: Stage with id 'publish-status' (2/3).
```

scenario proceeds as expected, the exception does not make sense though as there are only 3 agents attempting to connect (no extra orphaned processes or similar oddities found)

**Comment by sbaier1** [comment]
user errror 🤦‍♂
